-- 1. TIPOS ENUMERADOS (Para estandarizar y validar estados)
CREATE TYPE user_rol AS ENUM ('Administrador', 'Recepción', 'Médico', 'Enfermería');
CREATE TYPE estado_cita AS ENUM ('Pendiente', 'Confirmada', 'En espera', 'En atención', 'Atendida', 'Cancelada', 'No asistió');
CREATE TYPE prioridad_cita AS ENUM ('Baja', 'Media', 'Alta', 'Crítica');

-- 2. TABLA: usuarios_perfil
-- Conecta la autenticación de Supabase (auth.users) con los roles solicitados por el examen
CREATE TABLE usuarios_perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
    nombre TEXT NOT NULL,
    correo TEXT NOT NULL,
    rol user_rol NOT NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABLA: pacientes
-- Reemplaza el localStorage del módulo pacientes.js
CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE, -- Código único (Ej: PAC-001)
    nombres TEXT NOT NULL,
    apellidos TEXT NOT NULL,
    tipo_documento TEXT NOT NULL DEFAULT 'DNI',
    documento TEXT NOT NULL UNIQUE,
    fecha_nacimiento DATE NOT NULL,
    telefono TEXT,
    correo TEXT,
    direccion TEXT,
    alergias TEXT[], -- Mapeado directamente como un array de textos en PostgreSQL
    contacto_emergencia_nombre TEXT,
    contacto_emergencia_parentesco TEXT,
    contacto_emergencia_telefono TEXT,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABLA: citas
-- Manejo y programación de agendas médicas
CREATE TABLE citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE, -- Código de cita (Ej: CIT-102)
    paciente_id BIGINT REFERENCES pacientes(id) ON DELETE CASCADE,
    especialidad TEXT NOT NULL,
    medico TEXT NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    motivo TEXT,
    prioridad prioridad_cita DEFAULT 'Baja',
    justificacion_prioridad TEXT,
    estado estado_cita DEFAULT 'Pendiente',
    fecha_creacion TIMESTAMPTZ DEFAULT NOW(),
    
    -- VALIDACIÓN OBLIGATORIA: Evita que el mismo médico sea asignado a dos citas a la misma fecha y hora
    CONSTRAINT cita_medico_tiempo_unico UNIQUE (medico, fecha, hora)
);

-- 5. TABLA: sala_espera
-- Almacena las citas confirmadas por el personal de Recepción
CREATE TABLE sala_espera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT REFERENCES citas(id) ON DELETE CASCADE UNIQUE, -- Una cita no puede duplicarse en sala
    hora_llegada TIME NOT NULL DEFAULT CURRENT_TIME,
    estado TEXT DEFAULT 'Esperando',
    orden_prioridad INT DEFAULT 1
);

-- 6. TABLA: historial_consultas
-- Módulo final donde el Médico registra la atención (Conectado con historial.js)
CREATE TABLE historial_consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT REFERENCES pacientes(id) ON DELETE CASCADE,
    cita_id BIGINT REFERENCES citas(id) ON DELETE CASCADE UNIQUE, -- VALIDACIÓN OBLIGATORIA: No duplicar historial por cita
    medico TEXT NOT NULL,
    especialidad TEXT NOT NULL,
    fecha_atencion DATE NOT NULL DEFAULT CURRENT_DATE,
    sintomas TEXT NOT NULL,
    diagnostico TEXT NOT NULL,
    tratamiento TEXT NOT NULL,
    medicamentos JSONB DEFAULT '[]'::jsonb, -- Almacena arreglos de objetos complejos (nombre, dosis, etc.)
    observaciones TEXT,
    proxima_cita DATE
);